config/routes.rb
Mobiletrap::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'signup',     to: 'users#new',        as: :signup
  get 'signin',     to: 'sessions#new',     as: :signin
  get 'demo',       to: 'sessions#demo',    as: :demo
  get 'signout',    to: 'sessions#destroy', as: :signout
  delete 'signout', to: 'sessions#destroy', as: :signout_delete
  get 'home',       to: 'sessions#index',   as: :dashboard
  get 'reset',      to: 'sessions#reset',   as: :reset
  get '/contactus',:to => 'admin/forms#new', :as => 'contactus'
    

  namespace :admin do
    resources :users
    resources :pages
    resources :forms, only: [:create, :new, :index, :show]
    resources :devices
    resources :messages
    resources :logs
    resources :apps
    resources :contacts
    resources :locations
    resources :images do
      get 'display/:version', :action => 'display', :as => 'display'
    end
    resources :audios do
      get 'display'
    end
    resources :videos do
      get 'display'
    end
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:index, :new, :create]
  resources :pages, only: [:show]

  root :to => "pages#show", :id => 'home'

end

app/views/admin/pages/_form.html.erb
<div class="col-sm-12">
<%= simple_form_for([:admin, @page], :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
  <%= f.error_notification %>

    
  <div class="form-group">
    <%= f.input :title, placeholder: 'Title', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.input :slug, placeholder: 'Slug', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <% #= f.input :body, :as  => :text, placeholder: 'Body', class: 'form-control', width: '100%', rows: 30, input_html: { class: 'form-control' } %>
    <%= f.bootsy_area :body, editor_options: { font_styles: true, emphasis: true, lists: true, html: true, link: true, image: true, color: true}, placeholder: 'Body', class: 'form-control', width: '100%', rows: 30, input_html: { class: 'form-control' } %>
  </div>
    
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/admin/pages/edit.html.erb
<div class="row">
  <div class="col-sm-5 col-md-6">
    <h1>Editing page</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-md-10">
    <%= render 'form' %>
  </div>
</div>
<br />
<div class="row">
  <div class="col-sm-5 col-md-6">
    <%= link_to 'Show', admin_page_path(@page), class: 'btn btn-success' %> |
    <%= link_to 'Back', admin_pages_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/admin/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.slug %></td>
        <td><%= page.body %></td>
        <td><%= link_to 'Show', admin_page_path(page) %></td>
        <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
        <td><%= link_to 'Destroy', admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin %>
<%= link_to 'New Page', new_admin_page_path, class: 'btn btn-success' %>
<% end %>

app/views/admin/pages/new.html.erb
<div class="row">
  <div class="col-sm-5 col-md-6">
    <h1>New page</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-md-10">
    <%= render 'form' %>
  </div>
</div>
<br />
<div class="row">
  <div class="col-sm-5 col-md-6">
    <%= link_to 'Back', admin_pages_path, class: 'btn btn-success' %>
  </div>
</div

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body %>
</p>


<%= link_to 'Edit', edit_admin_page_path(@page), class: 'btn btn-success' %> |
<%= link_to 'Back', admin_pages_path, class: 'btn btn-success' %>