config/routes.rb
Mobiletrap::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'signup',     to: 'users#new',        as: :signup
  get 'signin',     to: 'sessions#new',     as: :signin
  get 'demo',       to: 'sessions#demo',    as: :demo
  get 'signout',    to: 'sessions#destroy', as: :signout
  delete 'signout', to: 'sessions#destroy', as: :signout_delete
  get 'home',       to: 'sessions#index',   as: :dashboard
  get 'reset',      to: 'sessions#reset',   as: :reset
  get '/contactus',:to => 'admin/forms#new', :as => 'contactus'
    

  namespace :admin do
    resources :users
    resources :pages
    resources :forms, only: [:create, :new, :index, :show]
    resources :devices
    resources :messages
    resources :logs
    resources :apps
    resources :contacts
    resources :locations
    resources :images do
      get 'display/:version', :action => 'display', :as => 'display'
    end
    resources :audios do
      get 'display'
    end
    resources :videos do
      get 'display'
    end
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:index, :new, :create]
  resources :pages, only: [:show]

  root :to => "pages#show", :id => 'home'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :device
  validates :device, presence: true
  before_validation :set_device, on: :create

  mount_uploader :url, ImageUploader
  
  def device_imei=(device_imei)
    @device_imei = device_imei
  end

  def device_imei
    @device_imei
  end

  def set_device
    if !device_id.present? && device_imei.present?
      self.device_id = Device.find_by_imei(device_imei).id
    end
  end
end

app/controllers/admin/images_controller.rb
module Admin
  class ImagesController < BaseController
    before_action :set_image, only: [:show, :edit, :update, :destroy]
  
    # GET /images
    # GET /images.json
    def index
      @images ||= Image.where(device_id: selected_device).order(created_at: :desc)
      unless params[:start_time].blank?
        start_date = DateTime.parse("#{params[:start_time]} 00:00:00")
        @images = @images.where("created_at >= :start_time", {start_time: start_date})
      end

      unless params[:end_time].blank?
        end_date = DateTime.parse("#{params[:end_time]} 23:59:59")
        @images = @images.where("created_at <= :end_time", {end_time: end_date})
      end
    end
  
    # GET /images/1
    # GET /images/1.json
    def show
    end

    # GET /images/1/display/thumb
    # GET /images/1/display/thumb.json
    def display
      @image = Image.find(params[:image_id])
      send_file @image.url_url(params[:version]).to_s, :disposition => 'inline', :type=>"application/jpg", :x_sendfile=>true
    end
  
    # GET /images/new
    def new
      @image = Image.new
    end
  
    # GET /images/1/edit
    def edit
    end
  
    # POST /images
    # POST /images.json
    def create
      @image = Image.new(image_params)
  
      respond_to do |format|
        if @image.save
          format.html { redirect_to admin_image_path(@image), notice: 'Image was successfully created.' }
#          format.json { render action: 'show', status: :created, location: @image }
          format.json {render :json => { :success => :created}}
        else
          format.html { render action: 'new' }
#          format.json { render json: @image.errors, status: :unprocessable_entity }
          format.json { render :json => {:errors => @image.errors, :success => :failed}, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /images/1
    # PATCH/PUT /images/1.json
    def update
      respond_to do |format|
        if @image.update(image_params)
          format.html { redirect_to admin_image_path(@image), notice: 'Image was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /images/1
    # DELETE /images/1.json
    def destroy
      @image.destroy
      respond_to do |format|
        format.html { redirect_to admin_images_url }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_image
        @image = Image.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def image_params
        params.require(:image).permit(:uniqid, :title, :capture, :url, :reference, :device_id, :device_imei)
      end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/images/_form.html.erb
<div class="col-sm-6">
<%= simple_form_for([:admin, @image], :html => {:multipart => true, class: 'form-horizontal', role: 'form'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :uniqid, placeholder: 'Uniqid', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.input :title, placeholder: 'Title', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.input :capture, placeholder: 'Capture', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.file_field :url, placeholder: 'Upload', input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.association :device, label_method: :name, value_method: :id, include_blank: true, input_html: { class: 'form-control' } %>
  </div>
    
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/admin/images/edit.html.erb
<div class="row">
  <div class="col-sm-5 col-md-6">
    <h1>Editing image</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-md-10">
    <%= render 'form' %>
  </div>
</div>
<br />
<div class="row">
  <div class="col-sm-5 col-md-6">
    <%= link_to 'Show', admin_image_path(@image), class: 'btn btn-success' %> |
    <%= link_to 'Back', admin_images_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/admin/images/index.html.erb
<h3 class="page-title"><%= pluralize(@images.size, 'image') %> stored</h3>
<div class="row">
  <% @images.each do |image| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag admin_image_display_path(image.id, :medium), style: 'max-width: 100%;' %>
        <div class="caption">
          <h3><%= image.title %></h3>
          <div><%= image.capture.strftime("%d %B %Y") %></div>
          <% if current_user.admin %>
            <p>
            <%= link_to 'Edit', edit_admin_image_path(image), class: 'btn btn-success' %>
            <%= link_to 'Destroy', admin_image_path(image), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>
<% if current_user.admin %>
<%= link_to 'New Image', new_admin_image_path, class: 'btn btn-success' %>
<% end %>

app/views/admin/images/new.html.erb
<div class="row">
  <div class="col-sm-5 col-md-6">
    <h1>New image</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-md-10">
    <%= render 'form' %>
  </div>
</div>
<br />
<div class="row">
  <div class="col-sm-5 col-md-6">
    <%= link_to 'Back', admin_images_path, class: 'btn btn-success' %>
  </div>
</div

app/views/admin/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uniqid:</strong>
  <%= @image.uniqid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Capture:</strong>
  <%= @image.capture %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag admin_image_display_path(@image.id, :thumb) %>
</p>

<p>
  <strong>Device:</strong>
  <%= @image.device.name %>
</p>


<%= link_to 'Edit', edit_admin_image_path(@image), class: 'btn btn-success' %> |
<%= link_to 'Back', admin_images_path, class: 'btn btn-success' %>