config/routes.rb
Mobiletrap::Application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'signup',     to: 'users#new',        as: :signup
  get 'signin',     to: 'sessions#new',     as: :signin
  get 'demo',       to: 'sessions#demo',    as: :demo
  get 'signout',    to: 'sessions#destroy', as: :signout
  delete 'signout', to: 'sessions#destroy', as: :signout_delete
  get 'home',       to: 'sessions#index',   as: :dashboard
  get 'reset',      to: 'sessions#reset',   as: :reset
  get '/contactus',:to => 'admin/forms#new', :as => 'contactus'
    

  namespace :admin do
    resources :users
    resources :pages
    resources :forms, only: [:create, :new, :index, :show]
    resources :devices
    resources :messages
    resources :logs
    resources :apps
    resources :contacts
    resources :locations
    resources :images do
      get 'display/:version', :action => 'display', :as => 'display'
    end
    resources :audios do
      get 'display'
    end
    resources :videos do
      get 'display'
    end
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:index, :new, :create]
  resources :pages, only: [:show]

  root :to => "pages#show", :id => 'home'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :device
  validates :device, presence: true
  before_validation :set_device, on: :create

  mount_uploader :url, VideoUploader
  
  def device_imei=(device_imei)
    @device_imei = device_imei
  end

  def device_imei
    @device_imei
  end

  def set_device
    if !device_id.present? && device_imei.present?
      self.device_id = Device.find_by_imei(device_imei).id
    end
  end
end

app/controllers/admin/videos_controller.rb
module Admin
  class VideosController < BaseController
    before_action :set_video, only: [:show, :edit, :update, :destroy]
  
    # GET /videos
    # GET /videos.json
    def index
      @videos ||= Video.where(device_id: selected_device).order(created_at: :desc)
      unless params[:start_time].blank?
        start_date = DateTime.parse("#{params[:start_time]} 00:00:00")
        @videos = @videos.where("created_at >= :start_time", {start_time: start_date})
      end

      unless params[:end_time].blank?
        end_date = DateTime.parse("#{params[:end_time]} 23:59:59")
        @videos = @videos.where("created_at <= :end_time", {end_time: end_date})
      end
    end
  
    # GET /videos/1
    # GET /videos/1.json
    def show
      #render :layout => false
    end

    # GET /videos/1/display
    # GET /videos/1/display
    def display
      @video = Video.find(params[:video_id])
#      send_file @video.url_url.to_s, :disposition => 'inline', :type=>"application/video", :x_sendfile=>true
      send_file(@video.url_url.to_s, :disposition => 'inline', :stream => true, :file_name => @video.title)
    end
  
    # GET /videos/new
    def new
      @video = Video.new
    end
  
    # GET /videos/1/edit
    def edit
    end
  
    # POST /videos
    # POST /videos.json
    def create
      @video = Video.new(video_params)
  
      respond_to do |format|
        if @video.save
          format.html { redirect_to admin_video_path(@video), notice: 'Video was successfully created.' }
#          format.json { render action: 'show', status: :created, location: @video }
          format.json {render :json => { :success => :created}}
        else
          format.html { render action: 'new' }
#          format.json { render json: @video.errors, status: :unprocessable_entity }
          format.json { render :json => {:errors => @video.errors, :success => :failed}, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /videos/1
    # PATCH/PUT /videos/1.json
    def update
      respond_to do |format|
        if @video.update(video_params)
          format.html { redirect_to admin_video_path(@video), notice: 'Video was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @video.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /videos/1
    # DELETE /videos/1.json
    def destroy
      @video.destroy
      respond_to do |format|
        format.html { redirect_to admin_videos_url }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_video
        @video = Video.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def video_params
        params.require(:video).permit(:uniqid, :title, :capture, :url, :reference, :device_id, :device_imei)
      end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_form.html.erb
<div class="col-sm-6">
<%= simple_form_for([:admin, @video], :html => {:multipart => true, class: 'form-horizontal', role: 'form'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :uniqid, placeholder: 'Uniqid', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.input :title, placeholder: 'Title', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.input :capture, placeholder: 'Capture', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.file_field :url, placeholder: 'Upload', input_html: { class: 'form-control' } %>
  </div>
        
  <div class="form-group">
    <%= f.association :device, label_method: :name, value_method: :id, include_blank: true, input_html: { class: 'form-control' } %>
  </div>
    
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/admin/videos/edit.html.erb
<div class="row">
  <div class="col-sm-5 col-md-6">
    <h1>Editing video</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-md-10">
    <%= render 'form' %>
  </div>
</div>
<br />
<div class="row">
  <div class="col-sm-5 col-md-6">
    <%= link_to 'Show', admin_video_path(@video), class: 'btn btn-success' %> |
    <%= link_to 'Back', admin_videos_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/admin/videos/index.html.erb
<h3 class="page-title"><%= pluralize(@videos.size, 'video') %> stored</h3>

<div class="row">
  <% @videos.each do |video| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= video_tag admin_video_display_path(video.id), :width => "100%", :controls => true %>
        <div class="caption">
          <h3><%= video.title %></h3>
          <div><%= video.capture.strftime("%d %B %Y") %></div>
          <% if current_user.admin %>
            <p>
            <%= link_to 'Edit', edit_admin_video_path(video), class: 'btn btn-success' %>
            <%= link_to 'Destroy', admin_video_path(video), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>
<% if current_user.admin %>
<%= link_to 'New Video', new_admin_video_path, class: 'btn btn-success' %>
<% end %>

app/views/admin/videos/new.html.erb
<div class="row">
  <div class="col-sm-5 col-md-6">
    <h1>New video</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-md-10">
    <%= render 'form' %>
  </div>
</div>
<br />
<div class="row">
  <div class="col-sm-5 col-md-6">
    <%= link_to 'Back', admin_videos_path, class: 'btn btn-success' %>
  </div>
</div

app/views/admin/videos/show.html.erb
<%= jwplayer_assets %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Uniqid:</strong>
  <%= @video.uniqid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Capture:</strong>
  <%= @video.capture %>
</p>

<p>
  <strong>Video:</strong>
  <%= video_tag admin_video_display_path(@video.id), :size => "320x240", :controls => true %>
</p>

<p>
  <strong>Device:</strong>
  <%= @video.device.name %>
</p>

<%= link_to 'Edit', edit_admin_video_path(@video), class: 'btn btn-success' %> |
<%= link_to 'Back', admin_videos_path, class: 'btn btn-success' %>